// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb2n-IFo8AAVyBa8jinp9sy72d-76y7OU',
    appId: '1:391263790643:web:b56dfb1449369322252546',
    messagingSenderId: '391263790643',
    projectId: 'autenticacao-bd8de',
    authDomain: 'autenticacao-bd8de.firebaseapp.com',
    storageBucket: 'autenticacao-bd8de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWiBXXtXbaMmWv4rTT2Wi5g0xk32EPepU',
    appId: '1:391263790643:android:c71348089328a7f2252546',
    messagingSenderId: '391263790643',
    projectId: 'autenticacao-bd8de',
    storageBucket: 'autenticacao-bd8de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOvVvUmSBEwJ7MkWHoN4X-qAlrD_A05A',
    appId: '1:391263790643:ios:b4cb37ea3abb4026252546',
    messagingSenderId: '391263790643',
    projectId: 'autenticacao-bd8de',
    storageBucket: 'autenticacao-bd8de.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOvVvUmSBEwJ7MkWHoN4X-qAlrD_A05A',
    appId: '1:391263790643:ios:b4cb37ea3abb4026252546',
    messagingSenderId: '391263790643',
    projectId: 'autenticacao-bd8de',
    storageBucket: 'autenticacao-bd8de.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb2n-IFo8AAVyBa8jinp9sy72d-76y7OU',
    appId: '1:391263790643:web:ee57c463dee3f3a9252546',
    messagingSenderId: '391263790643',
    projectId: 'autenticacao-bd8de',
    authDomain: 'autenticacao-bd8de.firebaseapp.com',
    storageBucket: 'autenticacao-bd8de.firebasestorage.app',
  );
}
